highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Bruno Paixão Resume
name: Bruno Paixão
email: brunopaixao87@gmail.com
email_full: mailto:brunopaixao87@gmail.com
website: github.io/brunopaixao87
website_full: https://brunopaixao.dev
github: trending
twitter: twitter
tel: +55 79 999946413
tel_full: tel:+5579999946413
google_maps: ''
address:
  street: 44 Perth Street
  postcode: 
  city: Aracaju - SE
  country: Brazil
google_analytics: UA-135965173-1

# needed for travis-ci build
exclude: [vendor]
