highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Bruno Paixão Resume
name: Bruno Paixão
email: brunopaixao87@gmail.com
email_full: mailto:brunopaixao87@gmail.com
website: Bruno Paixão
website_full: https://brunopaixao.dev
github: brunopaixao87
twitter: brunopaixaodev
tel: +55 79 999956513
tel_full: tel:+5579999946413
google_maps: 'https://www.google.com.br/maps/place/Aracaju,+SE/@-11.0058313,-37.1731963,12z/data=!3m1!4b1!4m5!3m4!1s0x71ab04015be27cd:0x804434fd92ec3b36!8m2!3d-10.9472468!4d-37.0730823'
address:
  street: 44 Perth Street
  postcode: 
  city: Aracaju - SE
  country: Brasil
google_analytics: UA-135965173-1

# needed for travis-ci build
exclude: [vendor]
